// packages/machine-coding-content/src/problems/autocomplete/react/solution/src/App.tsx
import { useState } from "react";

const FRUITS = [
  "Apple",
  "Apricot",
  "Banana",
  "Blueberry",
  "Cherry",
  "Grape",
  "Mango",
  "Orange",
  "Peach",
  "Pear",
];

export default function App() {
  const [query, setQuery] = useState("");
  const [open, setOpen] = useState(false);

  const matches = query
    ? FRUITS.filter((f) => f.toLowerCase().includes(query.toLowerCase()))
    : [];

  const pick = (value: string) => {
    setQuery(value);
    setOpen(false);
  };

  return (
    <main style={{ fontFamily: "sans-serif", padding: "1rem", maxWidth: 320 }}>
      <h1>Autocomplete</h1>
      <input
        aria-label="Search fruit"
        value={query}
        onChange={(e) => {
          setQuery(e.target.value);
          setOpen(true);
        }}
        placeholder="Type a fruit…"
      />
      {open && query && (
        <ul
          role="listbox"
          style={{
            listStyle: "none",
            padding: 0,
            margin: "4px 0",
            border: "1px solid #ddd",
          }}
        >
          {matches.length === 0 ? (
            <li style={{ padding: "4px 8px", color: "#888" }}>No results</li>
          ) : (
            matches.map((m) => (
              <li key={m}>
                <button
                  type="button"
                  role="option"
                  aria-selected={false}
                  onClick={() => pick(m)}
                  style={{
                    width: "100%",
                    textAlign: "left",
                    padding: "4px 8px",
                    border: "none",
                    background: "none",
                    cursor: "pointer",
                  }}
                >
                  {m}
                </button>
              </li>
            ))
          )}
        </ul>
      )}
    </main>
  );
}

// packages/machine-coding-content/src/problems/autocomplete/svelte/solution/src/App.svelte
<script lang="ts">
  const FRUITS = [
    "Apple",
    "Apricot",
    "Banana",
    "Blueberry",
    "Cherry",
    "Grape",
    "Mango",
    "Orange",
    "Peach",
    "Pear",
  ];

  let query = $state("");
  let open = $state(false);

  const matches = $derived(
    query
      ? FRUITS.filter((f) => f.toLowerCase().includes(query.toLowerCase()))
      : [],
  );

  function pick(value: string) {
    query = value;
    open = false;
  }
</script>

<main style="font-family: sans-serif; padding: 1rem; max-width: 320px">
  <h1>Autocomplete</h1>
  <input
    aria-label="Search fruit"
    bind:value={query}
    oninput={() => (open = true)}
    placeholder="Type a fruit…"
  />
  {#if open && query}
    <ul
      role="listbox"
      style="list-style: none; padding: 0; margin: 4px 0; border: 1px solid #ddd"
    >
      {#if matches.length === 0}
        <li style="padding: 4px 8px; color: #888">No results</li>
      {:else}
        {#each matches as m (m)}
          <li>
            <button
              type="button"
              role="option"
              aria-selected={false}
              onclick={() => pick(m)}
              style="width: 100%; text-align: left; padding: 4px 8px; border: none; background: none; cursor: pointer"
            >
              {m}
            </button>
          </li>
        {/each}
      {/if}
    </ul>
  {/if}
</main>
