// packages/machine-coding-content/src/problems/todo-list/svelte/starter/src/App.svelte
<script lang="ts">
  // TODO:
  //  - track the list of todos and the input text in reactive state ($state)
  //  - "Add" (or Enter) appends the trimmed text; ignore empty input
  //  - each item has a "Delete" button that removes only that item
</script>

<main style="font-family: sans-serif; padding: 1rem; max-width: 420px">
  <h1>Todo List</h1>
  <form>
    <input aria-label="New todo" placeholder="Add a todo" />
    <button type="submit">Add</button>
  </form>
  <ul></ul>
</main>

// packages/machine-coding-content/src/problems/todo-list/react/starter/src/App.tsx
import { useState } from "react";

export default function App() {
  // TODO:
  //  - track the list of todos and the input text in state
  //  - "Add" (or Enter) appends the trimmed text; ignore empty input
  //  - each item has a "Delete" button that removes only that item
  return (
    <main style={{ fontFamily: "sans-serif", padding: "1rem", maxWidth: 420 }}>
      <h1>Todo List</h1>
      <form>
        <input aria-label="New todo" placeholder="Add a todo" />
        <button type="submit">Add</button>
      </form>
      <ul></ul>
    </main>
  );
}
