// packages/machine-coding-content/src/problems/tabs/vue/solution/src/App.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const TABS = [
  { id: "html", label: "HTML", content: "HyperText Markup Language" },
  { id: "css", label: "CSS", content: "Cascading Style Sheets" },
  { id: "js", label: "JS", content: "JavaScript, the language of the web" },
];

const active = ref(TABS[0].id);
const current = computed(() => TABS.find((t) => t.id === active.value) ?? TABS[0]);
</script>

<template>
  <main style="font-family: sans-serif; padding: 1rem">
    <h1>Tabs</h1>
    <div role="tablist" style="display: flex; gap: 4px">
      <button
        v-for="t in TABS"
        :key="t.id"
        type="button"
        role="tab"
        :aria-selected="t.id === active"
        @click="active = t.id"
        :style="{
          padding: '6px 12px',
          border: '1px solid #ccc',
          borderBottom: t.id === active ? '2px solid #3178c6' : '1px solid #ccc',
          background: t.id === active ? '#eef4fb' : '#fff',
          cursor: 'pointer',
        }"
      >
        {{ t.label }}
      </button>
    </div>
    <div role="tabpanel" style="padding-top: 8px">{{ current.content }}</div>
  </main>
</template>

// packages/machine-coding-content/src/problems/tabs/svelte/solution/src/App.svelte
<script lang="ts">
  const TABS = [
    { id: "html", label: "HTML", content: "HyperText Markup Language" },
    { id: "css", label: "CSS", content: "Cascading Style Sheets" },
    { id: "js", label: "JS", content: "JavaScript, the language of the web" },
  ];

  let active = $state(TABS[0].id);
  const current = $derived(TABS.find((t) => t.id === active) ?? TABS[0]);
</script>

<main style="font-family: sans-serif; padding: 1rem">
  <h1>Tabs</h1>
  <div role="tablist" style="display: flex; gap: 4px">
    {#each TABS as t (t.id)}
      <button
        type="button"
        role="tab"
        aria-selected={t.id === active}
        onclick={() => (active = t.id)}
        style="padding: 6px 12px; border: 1px solid #ccc; border-bottom: {t.id ===
        active
          ? '2px solid #3178c6'
          : '1px solid #ccc'}; background: {t.id === active
          ? '#eef4fb'
          : '#fff'}; cursor: pointer"
      >
        {t.label}
      </button>
    {/each}
  </div>
  <div role="tabpanel" style="padding-top: 8px">{current.content}</div>
</main>
